owner_secret = "99999"
owner_id = "100"
credential_id = "12345"
credential_type = "1"
credential_secret = "55555"
skill_levels = ["8", "7", "6", "5", "9"]
years_of_experience = "5"
education_level = "2"
certifications = ["111", "222", "333"]
issue_timestamp = "1700000000"
expiry_timestamp = "1800000000"
has_employment_proof = "0"
employment_merkle_proof = ["0", "0", "0", "0", "0", "0", "0", "0"]
employment_merkle_indices = ["0", "0", "0", "0", "0", "0", "0", "0"]
required_credential_type = "1"
min_skill_levels = ["7", "5", "4", "3", "6"]
min_experience_years = "3"
min_education_level = "2"
required_certification = "0"
required_employment_root = "0"
credential_commitment = "0x1c79f730f01c31e1ec1a2094bef6d8fc1cd9c2efd4c6fdf5d2da5c88dd416ed5"
current_timestamp = "1750000000"
